app:
  build: docker/app
  ports: 
    - 3000:3000
  links:
    - db
    - webpack
  volumes:
    - .:/app:cached

webpack:
  build: docker/webpack
  ports:
    - ${WEBPACK_DEV_SERVER_PORT}:${WEBPACK_DEV_SERVER_PORT}
  volumes:
    - .:/app:cached

db:
  image: postgres:9.4
  volumes_from:
    - dbdata
  environment:
    POSTGRES_DB: ${DATABASE_NAME}
    POSTGRES_USER: ${DATABASE_USERNAME}
    POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

dbdata:
  image: postgres:9.4
  entrypoint: "true"
